<div class="reveal">
    <div class="slides">
        <section>
            <h3 class="pb-title">catch() method</h3>
            <section data-auto-animate>
                <pre data-id="code-animation">
                    <code class="language-js bulbs-container-js" data-trim data-line-numbers="|5, 9|1-5,15-19"></code>
                </pre>
                <button class="fragment pb-next below" type="button" onclick="nextBranch('async-3-3-3')">2 go</button>
            </section>
            <section>
                <p>
                    When two errors occour, the <b>catch()</b> method handle only first one. Every next line after first error will not be invoked. <b>finally()</b> method will always be invoked both after success or error in Promise chain. Below is how will log from browser console look like.
                </p>
                <pre>
                    <code class="language-plaintext" data-trim>
                        1. setBulbColor
                        Error: Error 1
                        finally method
                    </code>
                </pre>
            </section>
        </section>
    </div>
</div>